### ISSUE TITLE
Blur on compact sidebar broken

### ISSUE THREAD

**Issue by DipsoNOR** [JustAdumbPrsn/Zen-Nebula#200]
### ⚠️ Preliminary Checks

- [x] I have read and understood the contribution guidelines.
- [x] I have searched the existing issues and this is not a duplicate.
- [x] I have tested this without any other Zen Mods enabled.
- [x] I can confirm this bug is reproducible with Nebula and does not occur when Nebula is disabled.

### What happened?

Compact mode suddenly seems to be just plain transparent without any blur (making it really hard to use)

### Steps to Reproduce

Enable Compact mode.

### Nebula Version

3.1

### Zen Browser Version

1.13.2b

### Operating System

Windows - x64

### Affected Component(s)

Compact Mode

### Screenshots or Videos

<img width="269" height="334" alt="Image" src="https://github.com/user-attachments/assets/04f8b95b-2870-4d7c-8882-802892bd0ff9" />

**Comment by SannyTusk16** [comment]
Same here

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/ca51e3b1-b4a5-4fa7-a68c-faf3655de1bb" />

**Comment by JustAdumbPrsn** [comment]
yes this is because of sine, the update should also download a nebula.uc.js file which sine is not
im currently troubleshooting this

**Comment by teaongsi** [comment]
same for me

<img width="190" height="223" alt="Image" src="https://github.com/user-attachments/assets/e5fffcb8-187b-4b47-bbcf-d8a1ff69ab7d" />

**Comment by Sierakk** [comment]
Same here 🤷

<img width="355" height="234" alt="Image" src="https://github.com/user-attachments/assets/5ed5b756-9fcf-42c5-b286-902c2987e83b" />

**Comment by JustAdumbPrsn** [comment]
should be fixed now, just remove and download nebula again @Sierakk

**Comment by nuwminus** [comment]
> should be fixed now, just remove and download nebula again [@Sierakk](https://github.com/Sierakk)

i can't even remove mods from sine, the button turns dark gray then after a few seconds it turns light gray yet again 

<img width="606" height="116" alt="Image" src="https://github.com/user-attachments/assets/dcfa35e8-c669-4ee4-8060-a7aa65fb7dc2" />

**Comment by leoufort** [comment]
It's still doing it after the update, rolling back to v3 (before .js implementation) makes it look blurred again

**Comment by autrioly** [comment]
still going on after an update and a sine fresh install

**Comment by JustAdumbPrsn** [comment]
@CosmoCreeper 
:(((

**Comment by CosmoCreeper** [comment]
@DipsoNOR did you remove Nebula and reinstall it? Did it say that a mod with js was installed?

**Comment by autrioly** [comment]
@CosmoCreeper  for me it does said that a mod with js is installed but I can't even remove a mode , try restart zen but nothing

**Comment by CosmoCreeper** [comment]
@@Chandol-With-Uke r u up-to-date with Sine? Latest Sine fixes that issue with removing the mod.

**Comment by autrioly** [comment]
@CosmoCreeper  yeah sorry bothering you it was the chrome folder not owned by my user , thanks for your great job you two

**Comment by Munkhu1** [comment]
The `Remove mod` option is grayed out for me. I'm using sine. Any ideas?

<img width="619" height="132" alt="Image" src="https://github.com/user-attachments/assets/0e607592-4508-4a05-b49f-f4b0da2a8fe6" />

**Comment by CosmoCreeper** [comment]
@Munkhu1 That will be fixed in a new update today.

**Comment by Munkhu1** [comment]
@CosmoCreeper Thanks for the fast reply. Is it also going to fix the full transparent sidebar issue? Mine is still fully transparent. I tried the mod without sine as well. But the sidebar was still fully transparent.

**Comment by CosmoCreeper** [comment]
@Munkhu1 From what I know, that's just an issue with older Nebula installs and by reinstalling, it should fix itself.

**Comment by Munkhu1** [comment]
I'm pretty sure i deleted every file related to Nebula (everything) in my chrome folder but it still doesn't work. Hope I'm not doing smth wrong.

**Comment by CosmoCreeper** [comment]
@Munkhu1 New update out now so you should be able to remove it!

**Comment by Munkhu1** [comment]
That's great! But i still don't think it's gonna work since it didn't work without sine? I just downloaded a bunch of mods and configured them without sine so kinda lazy to do all that again in sine.

**Comment by CosmoCreeper** [comment]
@Munkhu1 I think that Sine + external mods will work regardless. The issue with installing Nebula outside of Sine is that the JS is not applied, which Nebula relies on for that compact mode. If you use Sine and it works properly, the issue should go away.

**Comment by Munkhu1** [comment]
@CosmoCreeper oh, so the new version is supposed to be used with sine? Is it not possible to use it without sine? I assume sine will use my already set preferences for my mods so I'll try using nebula with sine in a moment. Thanks for the info.

**Comment by Munkhu1** [comment]
I just tried it with sine and it works! So did I install Nebula wrong when I first tried it without sine? Or is the new version supposed to work only with sine? I'm a bit confused. But at last, it worked.

**Comment by CosmoCreeper** [comment]
@Munkhu1 yeah, the author recommends using Sine now, but there is a way to use it without Sine.

To use it without Sine, you have to grab the Nebula.uc.js file from the Nebula folder in the mods folder of the sine marketplace, and place it in your JS folder where sine.uc.mjs is located.

**Comment by Munkhu1** [comment]
Alright, thanks a lot for the help. Just a random question, is there any way to make the [Better CtrlTab Panel](https://github.com/psu/zen-mods) bigger? It got smaller after installing Nebula. I'm prob asking the question in the wrong place. But giving it a shot.

![Image](https://github.com/user-attachments/assets/2988f097-238f-450b-a9f3-f8edca3c7fee)

Increasing the `General - Zoom (1.0 = Full width 0.5 = 25% space on each side)` in it's config squishes everything:

![Image](https://github.com/user-attachments/assets/dfdad78d-0707-42eb-bc09-185d81b39b71)

**Comment by CosmoCreeper** [comment]
@Munkhu1 nah, no idea. Ive used it once, but never messed with it too much.

**Comment by Munkhu1** [comment]
Understandable. Thanks again, have a great one.

**Comment by leoufort** [comment]
it works now :) 
is there a way to change the compact sidebar width in the js? there was a line in the nebula config before but now it's gone

**Comment by JustAdumbPrsn** [comment]
@leoufort the compact sidebar width is now not fixed, its the way default zen handles it
basically the normal sidebar width is the same as compact sidebar width if you increase regular width then compact mode will also increase

**Comment by ryadios** [comment]
@CosmoCreeper Hey is it possible if you could provide the direct link for the sine markeplace nebula js file?

**Comment by CosmoCreeper** [comment]
@SNKYNinja 
https://github.com/sineorg/store/tree/main/mods/Nebula/Nebula.uc.js

**Comment by DipsoNOR** [comment]
Ok, got everything back to working state now.

Sine was suddenly also broken due to it not being able to write to a file. 

Renamed the offending files, reinstalled sine, 

Removed nebula - Restarted
Reinstalled nebula - restarted.
Back in business.

**Comment by CosmoCreeper** [comment]
@DipsoNOR Glad to hear its working again! Note that an old version was giving Sine some troubles so I had to fix it, but due to that error auto-updating was broken.

**Comment by SannyTusk16** [comment]
what are the offending files??

**Comment by TUGMindboggle** [comment]
this seems to be fixed for me, but the same problem is present elsewhere in many context menus in zen, as seen below

<img width="935" height="638" alt="Image" src="https://github.com/user-attachments/assets/7e764399-d089-4a82-95d9-8b813a3a26bd" />

<img width="120" height="179" alt="Image" src="https://github.com/user-attachments/assets/63195ffb-0df8-4320-90bf-de923055cb8b" />

**Comment by Munkhu1** [comment]
@TUGMindboggle Are you using better context menu mod?

**Comment by TUGMindboggle** [comment]
@Munkhu1 i'm not. turning off all other mods makes no difference unfortunately

**Comment by Munkhu1** [comment]
Same thing was happening to me on linux unless i turned off better context menu. It was fine with the mod on Windows tho.

**Comment by JustAdumbPrsn** [comment]
this is happening if you guys do not have the nebula.js file along with the stuff needed to make it working

<img width="295" height="769" alt="Image" src="https://github.com/user-attachments/assets/d8f74a4a-7efa-46d8-8520-aff6bd821466" />

**Comment by AlwaysBorderRadius** [comment]
@JustAdumbPrsn can you please make a detailed guide on how to fix this issue? (not having blur behind context menus and popups)
I have spend several hours, trying different things based on what I have read on these threads (removing nebula, restarting, installing it again from sine, restarting, not working, renaming the `Nebula_Nebula.uc.js` and `.bd` files to `Nebula.uc.js` and `.bd`... also sine mods disappearing from time to time... updating it does nothing... @CosmoCreeper is there a way to fix that too?)

**Comment by CosmoCreeper** [comment]
@AlwaysBorderRadius press ctrl+shift+j in zen and see if there are any errors.

**Comment by AlwaysBorderRadius** [comment]
@CosmoCreeper 

<img width="2175" height="1886" alt="Image" src="https://github.com/user-attachments/assets/3d3aadef-715e-4152-a7da-7dd32c81f191" />

**Comment by CosmoCreeper** [comment]
@AlwaysBorderRadius 
Go to your profile folder > chrome folder, and run this command:
`sudo chown {user}:{user} ./JS && sudo chown {user}:{user} ./JS/engine`
Remember to replace {user} with your username on Linux.

**Comment by AlwaysBorderRadius** [comment]
@CosmoCreeper I'm not on linux, I'm on windows ._.

**Comment by CosmoCreeper** [comment]
@AlwaysBorderRadius oh. Do you have discord? I have several ppl on the Sine server with this issue and i have yet to find the solution.

**Comment by AlwaysBorderRadius** [comment]
@CosmoCreeper yes I have. I just joined the Sine server, in case you prefer to continue there

**Comment by CosmoCreeper** [comment]
@AlwaysBorderRadius what's your username?
