### ISSUE TITLE
Multiple bugs with Sine Search bar blur doesn't disappear upon closing | Settings page isn't frosted/blurred like it used to be | and compact sidebar has this purple dark color instead of black

### ISSUE THREAD

**Issue by AerinUWU** [JustAdumbPrsn/Zen-Nebula#273]
### ⚠️ Preliminary Checks

- [x] I have read and understood the contribution guidelines.
- [x] I have searched the existing issues and this is not a duplicate.
- [x] I have tested this without any other Zen Mods enabled.
- [x] I can confirm this bug is reproducible with Nebula and does not occur when Nebula is disabled.

### What happened?

Hello,

So I encountered 3 issues upgrading Nebula using Sine for the first time

1. First issue is the search that doesn't disappear even after closing it that is how it looks like when you press CTRL+F

<img width="2289" height="66" alt="Image" src="https://github.com/user-attachments/assets/f818996d-c437-4f56-bed3-6a147a850c5b" />

And here is how it looks when I try to close it

<img width="2295" height="68" alt="Image" src="https://github.com/user-attachments/assets/b766a173-db0c-4896-be8b-963837426e26" />

2. Basically as the title said the settings page isn't blurred whatsoever and in fact isn't even black like without the theme

<img width="1052" height="1228" alt="Image" src="https://github.com/user-attachments/assets/1ae21bbf-ddec-41f4-9a8b-bacd49dc6d73" />

3. Lastly the compacted sidebar doesn't have the default black color scheme

<img width="273" height="1185" alt="Image" src="https://github.com/user-attachments/assets/df649b43-2e3c-4bea-bab8-158fb9434b4b" />

### Nebula Version

V3.3

### Zen Browser Version

1.16b

### Operating System

Windows - x64

### Affected Component(s)

Compact Mode

**Comment by Meti0X7CB** [comment]
Same issue for me.

**Comment by JustAdumbPrsn** [comment]
let me try fix settings page

**Comment by JustAdumbPrsn** [comment]
also for the search bar thing, someone made  a pr which i just merged so it should be fine

**Comment by AerinUWU** [comment]
Good to hear from you man hope everything is going well for you unfortunately everything I mentioned is still broken and now it's even more broken with the example of issue #290

**Comment by JustAdumbPrsn** [comment]
fixed :))

**Comment by AerinUWU** [comment]
Thank you for fixing most of the bugs but the purplish compact sidebar is still present
